services:
  database:
    image: postgis/postgis:13-master
    container_name: backend-db
    restart: always
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'backend'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'backend'

  cache:
    image: redis:6
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/cache:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: 6379

  backend:
    image: directus/directus:10.13.1
    container_name: backend
    restart: always
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'backend'
      DB_USER: 'backend'
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # These is helpful for local developement but should probably be removed in production
      CORS_ENABLED: 'true'
      REFRESH_TOKEN_COOKIE_DOMAIN: 'localhost'
      EXTENSIONS_AUTO_RELOAD: 'true'

      WEBSOCKETS_ENABLED: 'true'
      # The default config prevents importing files from 0.0.0.0. See https://docs.directus.io/self-hosted/config-options.html#security . This can be removed in production but in local development it is recommended to keep it so you can import logos from Organization > website.
      IMPORT_IP_DENY_LIST: ''

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'
